name: Setup action
description: Reusable action to setup node and install packages

runs:
  using: "composite"
  steps:

    - name: Install Node.js
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
      with:
        node-version: 24.21.0
        package-manager-cache: false

    - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
      name: Install pnpm
      with:
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      run: |
        echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
      shell: bash

    - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: pnpm-store-${{ hashFiles('**/package.json') }}
        restore-keys: |
          pnpm-store-

    - name: Install dependencies
      run: pnpm install
      shell: bash

    - name: Cache turbo
      uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-
