packages:
  - packages/backend/apps/*/*
  - packages/backend/libraries/*
  - packages/backend/tools/*
  - packages/libraries/*

ignoredBuiltDependencies:
  - '@prisma/engines'
  - prisma

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
